AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: A template that creates the Lambda layers in this repo.
Resources:
  Requests:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: requests
      Description: Dependencies for the requests library.
      ContentUri: python/requests/.
      CompatibleRuntimes:
        - python3.8
        
  Xendit:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: xendit
      Description: Dependencies for the xendit SDK.
      ContentUri: python/xendit/.
      CompatibleRuntimes:
        - python3.8
        
  Data:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: data
      Description: Dependencies for some data tools.
      ContentUri: python/data/.
      CompatibleRuntimes:
        - python3.8
